"""Add price_usd column to contracts table

Revision ID: 4d29ce4eb87e
Revises: 9d12ee69908b
Create Date: 2025-01-06 06:56:17.752873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d29ce4eb87e'
down_revision = '9d12ee69908b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_contracts')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_usd', sa.Float(), nullable=True))
        batch_op.alter_column('contract_address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('base_token_address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('quote_token_address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('chain_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('dex_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('dex_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('chain_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('quote_token_address',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('base_token_address',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('contract_address',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('price_usd')

    op.create_table('_alembic_tmp_contracts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contract_address', sa.VARCHAR(length=100), nullable=False),
    sa.Column('base_token_address', sa.VARCHAR(length=100), nullable=False),
    sa.Column('quote_token_address', sa.VARCHAR(length=100), nullable=False),
    sa.Column('chain_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dex_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('price_native', sa.FLOAT(), nullable=True),
    sa.Column('base_token_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('quote_token_name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_address')
    )
    # ### end Alembic commands ###
