"""Added price_native to Contracts model

Revision ID: 64710b7249e7
Revises: 
Create Date: 2025-01-06 04:11:45.257071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64710b7249e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_native', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('price_native')

    # ### end Alembic commands ###
