"""add token names to contracts

Revision ID: 9d12ee69908b
Revises: ed91651b9169
Create Date: 2025-01-06 05:45:18.892554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d12ee69908b'
down_revision = 'ed91651b9169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_contracts')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_token_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('quote_token_name', sa.String(length=100), nullable=False))
        batch_op.alter_column('chain_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('dex_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('dex_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('chain_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('quote_token_name')
        batch_op.drop_column('base_token_name')

    op.create_table('_alembic_tmp_contracts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contract_address', sa.VARCHAR(length=100), nullable=False),
    sa.Column('base_token_address', sa.VARCHAR(length=100), nullable=False),
    sa.Column('quote_token_address', sa.VARCHAR(length=100), nullable=False),
    sa.Column('chain_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dex_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('price_native', sa.FLOAT(), nullable=False),
    sa.Column('base_token_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('quote_token_name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_address')
    )
    # ### end Alembic commands ###
