"""add fields to contracts table

Revision ID: ed91651b9169
Revises: 64710b7249e7
Create Date: 2025-01-06 05:32:11.150850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed91651b9169'
down_revision = '64710b7249e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_token_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('quote_token_name', sa.String(length=100), nullable=False))
        batch_op.alter_column('chain_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('dex_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('price_native',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('price_native',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('dex_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('chain_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('quote_token_name')
        batch_op.drop_column('base_token_name')

    # ### end Alembic commands ###
